apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    service: backend
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
    app.kubernetes.io/name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: backend
      app: backend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: backend
        app: backend
    spec:
      containers:
        - name: backend
          image: sgccr.ccs.tencentyun.com/intl-backend/intlnh:v5
          imagePullPolicy: IfNotPresent
          command: ["sh",'cd /data/home/user00/nginx/sbin/ && ./nginx -g \"daemon off;\"']
          ports:
            - containerPort: 9080
          readinessProbe:
            tcpSocket:
              port: 9080
            initialDelaySeconds: 5
            periodSeconds: 10
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
      dnsPolicy: Default

---

